/**
 * Lens Service v3 - Type Exports
 */

// Configuration Types
export type {
  ServiceConfig,
  LLMConfig,
  LLMProvider,
  AzureOpenAIConfig,
  OpenAIConfig,
  AnthropicConfig,
  EmbeddingConfig,
  EmbeddingProvider,
  DatabaseConfig,
  RedisConfig,
  TelegramConfig,
  AgentConfig,
  RetrievalConfig,
  RerankerConfig,
  CoRetrievalConfig,
} from './config';

// Agent Types
export type {
  AgentType,
  AgentDefinition,
  AgentOutput,
  SupervisorState,
  AgentCallRecord,
  ToolCallRecord,
  SupervisorDecision,
  ConversationMessage,
  ConversationRole,
  AgentContext,
} from './agent';

// Skill Types
export type {
  SkillDefinition,
  PreActionType,
  PreAction,
  ScrapeUrlsConfig,
  SearchDatabaseConfig,
  CallApiConfig,
  LoadContextConfig,
  PreActionConfig,
  PostActionType,
  PostAction,
  AutoGeneratePageConfig,
  SendNotificationConfig,
  SaveToDatabaseConfig,
  TriggerWebhookConfig,
  PostActionConfig,
  PostActionCondition,
  SkillExecutionContext,
  PreActionResult,
  SkillExecutionResult,
  PostActionResult,
  SkillRegistryEntry,
} from './skill';

// Retrieval Types
export type {
  Document,
  DocumentContentType,
  DocumentEmbedding,
  QueryEmbedding,
  SearchOptions,
  SearchMode,
  SearchFilters,
  SearchResult,
  ScoreBreakdown,
  RerankOptions,
  RerankResult,
  FeedbackEvent,
  FeedbackSource,
  CoRetrievalMatrixEntry,
  UsageVectorUpdateJob,
  HybridRetrievalPipeline,
  BM25RetrieverConfig,
  VectorRetrieverConfig,
  FusionStrategy,
  FusionWeights,
  RerankerConfig as RerankerPipelineConfig,
} from './retrieval';

// Database Types
export type {
  TableSchema,
  ColumnSchema,
  ColumnType,
  ForeignKeyRef,
  TablePermissions,
  TableRelationship,
  TableIndex,
  QueryOptions,
  OrderByClause,
  JoinClause,
  QueryResult,
  InsertOptions,
  UpdateOptions,
  DeleteOptions,
  MutationResult,
  TransactionContext,
  TransactionQuery,
  QueryValidationResult,
  ValidationError,
  ValidationWarning,
  PoolStatus,
} from './database';

// Tool Types
export type {
  ToolDefinition,
  ToolCategory,
  ToolExecutionContext,
  ToolExecutionResult,
  SearchKnowledgeBaseInput,
  SearchKnowledgeBaseOutput,
  ExecuteSQLInput,
  ExecuteSQLOutput,
  UpdateRecordInput,
  UpdateRecordOutput,
  GeneratePageInput,
  PageBlock,
  PageBlockType,
  GeneratePageOutput,
  SemanticSearchInput,
  SemanticSearchOutput,
  FindSimilarItemsInput,
  FindSimilarItemsOutput,
  RecordFeedbackInput,
  RecordFeedbackOutput,
  QueryElementsInput,
  ElementInfo,
  QueryElementsOutput,
  ClickElementInput,
  ClickElementOutput,
  InputTextInput,
  InputTextOutput,
  GetPageSummaryInput,
  PageSummary,
  SendNotificationInput,
  SendNotificationOutput,
  ScrapeUrlInput,
  ScrapeUrlOutput,
} from './tools';

// Page Types
export type {
  GeneratedPage,
  PageMetadata,
  PageTheme,
  PageBlockData,
  BlockType,
  BlockProps,
  HeroBlockProps,
  ProductGridBlockProps,
  ProductItem,
  ProductCardBlockProps,
  TestimonialBlockProps,
  CTABlockProps,
  TextBlockProps,
  ImageBlockProps,
  VideoBlockProps,
  ComparisonTableBlockProps,
  ComparisonRow,
  FAQBlockProps,
  FAQItem,
  FeaturesBlockProps,
  FeatureItem,
  StatsBlockProps,
  StatItem,
  FooterBlockProps,
  FooterLinkGroup,
  SocialLink,
  CustomHTMLBlockProps,
  PageBuilderContext,
  BlockRenderer,
  ValidationResult,
  PageStorageOptions,
  StoredPage,
} from './page';
