version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: lens-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lens_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lens_service"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

